import type { MetadataRoute } from "next";

/**
 * PWA manifest. Slice 1 shipped the fields below as a valid installable
 * candidate; Slice 12 is what makes the promise real — `public/sw.js`
 * (registered from the (client) layout only) provides the offline cached
 * shell + last-viewed browse data, and installability is verified there via
 * Lighthouse's PWA audit rather than asserted from the manifest alone.
 *
 * Icons are generated by `npm run icons:generate` (scripts/generate-icons.mjs)
 * from the Part F3 palette — placeholder art, replaced when real brand artwork
 * exists (Slice 12 did not source new photography; see its Implementation
 * notes). `start_url` is the client marketplace root: the seller dashboard
 * lives on a different host entirely (portal.apoyolime.com/food) and is never
 * the installed app's entry point.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Apoyo Food",
    short_name: "Apoyo Food",
    description:
      "Discover food made by independent creators in Trinidad & Tobago — home cooks, bakers, dessert makers and caterers near you.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F4EEE1", // --cream-bg
    theme_color: "#536D46", // --green, the anchor accent
    categories: ["food", "shopping", "lifestyle"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
