import type { MetadataRoute } from "next";

/**
 * PWA manifest — a STUB, per Slice 1. Architecture Part C puts the PWA in the
 * MVP (manifest, icons, installability, offline browse shell) and Slice 12
 * finalises it: installability verification, the offline cached shell and
 * last-viewed browse data all land there. What is here now is the minimum that
 * makes the app a valid installable candidate with on-palette chrome.
 *
 * Icons are generated by `npm run icons:generate` (scripts/generate-icons.mjs)
 * from the Part F3 palette — placeholder art, replaced when real brand artwork
 * exists. `start_url` is the client marketplace root: the seller dashboard lives
 * on a different host entirely (portal.apoyolime.com/food) and is never the
 * installed app's entry point.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Apoyo Food",
    short_name: "Apoyo Food",
    description:
      "Discover food made by independent creators in Trinidad & Tobago — home cooks, bakers, dessert makers and caterers near you.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#F4EEE1", // --cream-bg
    theme_color: "#536D46", // --green, the anchor accent
    categories: ["food", "shopping", "lifestyle"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
